AWSTemplateFormatVersion: 2010-09-09
Description: IAM role for Cresta S3 Bucket Data Access
Parameters:
  ExternalId:
    Description: >-
      External ID for the data access role (ask your Cresta account manager)
    Type: String
    AllowedPattern: .+
    ConstraintDescription: ExternalId is required
  SourceBucketName:
    Description: >-
      The contents of this bucket will be shared with Cresta
    Type: String
    AllowedPattern: .+
    ConstraintDescription: BucketName is required
  IAMRoleName:
    Description: Customize the name of IAM role for ingesting/sending data to Cresta
    Type: String
    Default: CrestaIngestionRole
  CrestaAWSAccountIds:
    Description: >-
      Comma separated list of AWS account IDs allowed to assume the IAM role. DO NOT CHANGE!
    Type: CommaDelimitedList
    Default: 510370324380,488350602631,730335187493,975050116558,302217641952,107136125828
  WriteAccess:
    Description: >-
      Allow Cresta to write to the bucket
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
Conditions:
  WriteAccessCondition: !Equals
    - !Ref WriteAccess
    - "true"
Resources:
  CrestaIngestionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - arn:aws:iam::${account}:root
                  - account:
                      !Join
                      - ":root,arn:aws:iam::"
                      - !Ref CrestaAWSAccountIds
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref ExternalId
      RoleName: !Ref IAMRoleName
      Policies:
        - PolicyName: CrestaIngestionSrcPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Resource:
                - !Sub "arn:aws:s3:::${SourceBucketName}"
                - !Sub "arn:aws:s3:::${SourceBucketName}/*"
              Action:
                - "s3:Get*"
                - "s3:List*"
        - !If
          - WriteAccessCondition
          - PolicyName: CrestaIngestionSrcWritePolicy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:s3:::${SourceBucketName}/*"
                Action:
                  - "s3:Put*"
                  - "s3:Delete*"
          - !Ref "AWS::NoValue"
Outputs:
  ExternalId:
    Description: External ID for the data access role
    Value: !Ref ExternalId
  SourceBucketName:
    Description: S3 Bucket with source data for transfer
    Value: !Ref SourceBucketName
  IAMRoleName:
    Description: AWS IAM Role named to be used with Cresta Data Ingestion
    Value: !Ref CrestaIngestionRole
  AccountId:
    Description: AWS Account number
    Value: !Ref "AWS::AccountId"
  RoleArn:
    Description: Arn of Created Role
    Value: !GetAtt CrestaIngestionRole.Arn
  Region:
    Description: AWS Region
    Value: !Ref "AWS::Region"
  WriteAccess:
    Description: WriteAccess
    Value: !Ref WriteAccess
