name: cfn-lint
on:
  - push
jobs:
  cfn-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: cfn-lint
      uses: scottbrenner/cfn-lint-action@v2.3.4
      with:
        args: "**/*.yaml"
