name: Push to S3

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  push:
    name: Push
    runs-on: [self-hosted, cpu]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get AWS Credentials
        uses: cresta/action-vault-aws-credentials@v0.0.8
        with:
          aws-account-name: ${{ secrets.AWS_ACCOUNT_NAME }}
          vault-role: ${{ secrets.VAULT_ROLE }}
          vault-address: ${{ secrets.VAULT_ADDRESS }}

      - name: Push to S3
        run: |
          aws s3 cp ./aws s3://${{ secrets.CRESTA_CLOUDFORMATION_S3_BUCKET }}/allow-cresta-s3-data-transfer/aws --recursive
